Fix error in checking existing VMs

diff --git a/.github/workflows/createBuiltTiles.yml b/.github/workflows/createBuiltTiles.yml
--- a/.github/workflows/createBuiltTiles.yml
+++ b/.github/workflows/createBuiltTiles.yml
@@ -24,17 +24,18 @@ jobs:
       - name: Create Compute Engine Instance
         run: |
           # Check if the VM exists
-          VM_EXISTS=$(gcloud compute instances list --filter="name=nw-analysis-vm-built" --format="count[no-pad]")
-      
+          gcloud compute instances list --filter="name=nw-analysis-vm-built" | grep "nw-analysis-vm-built"
+          VM_EXISTS=$?  # Exit status of grep (0 if found, 1 if not found)
+          
           # Create the VM if it doesn't exist
-          if [ "$VM_EXISTS" -eq "0" ]; then
+          if [ "$VM_EXISTS" -ne "0" ]; then
             gcloud compute instances create nw-analysis-vm-built \
               --zone=europe-west9-a \
               --machine-type=e2-standard-8 \
               --image=debian-11-bullseye-v20230629 \
               --image-project=debian-cloud
           fi
-
+        
       - name: Upload Service Account Key to VM
         run: |
           echo "${{ secrets.GCP_SA_KEY }}" > key.json
